linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic
    - gofmt
    - goimports
    - misspell
    - revive

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

issues:
  exclude-rules:
    - path: _test\.go
      text: "Error return value is not checked"
      linters:
        - errcheck